Tty dev
XCSoar/XCSoar pull request #1035
Opened 2022-08-31 14:10 UTC by iltis42

Brief summary of the changes
----------------------------

- Move IsCharDev() utility as already present in TTYPort also in the TTYEnumerator, so we move this one liner to FileUtil. 
- Use generic IsCharDev() in TTYEnumerator to solve #1012 

Related issues and discussions
------------------------------
#1012 
#1034  (closed, replaced by this)

2022-08-31 14:25 UTC, MaxKellermann requested changes
There is text in the PR that is nowhere to be found in the commit messages, and that's always a bad sign. A good PR has **no text at all**!

2022-08-31 14:50 UTC, MaxKellermann commented
The PR has grown from 2 to 5 commits, all of which are bad.

2022-08-31 14:51 UTC, iltis42 commented on src/system/FileUtil.cpp
> +  DWORD attributes = GetFileAttributes(path.c_str());
Not yet had time to compile for Windows, it was compiled for ANDROID and tested on the real board, CI should have shown this to us.

2022-08-31 14:52 UTC, iltis42 commented
> The PR has grown from 2 to 5 commits, all of which are bad.

If the content is okay, i can quickly cleanup into a single one.

2022-08-31 15:00 UTC, MaxKellermann commented on src/system/FileUtil.cpp
> +  DWORD attributes = GetFileAttributes(path.c_str());
If you write code that is explicitly specific to Windows, I expect you to compile and test it before you submit it for review, or else you'll just waste my time. Compiling is not enough, CI is not enough, CI wouldn't catch runtime errors.

2022-08-31 15:03 UTC, iltis42 commented on src/system/FileUtil.cpp
> +  DWORD attributes = GetFileAttributes(path.c_str());
This wasn't my intension, removed this specific part, i am not very familiar with Windows. The generic posix part should do IMHO.

2022-08-31 15:03 UTC, MaxKellermann commented
> Since this function will never be used on Windows, just omit it there.

... which you did not, instead of omitted the preprocessor check, and now the Windows build is broken again.

2022-08-31 15:05 UTC, MaxKellermann commented on src/system/FileUtil.cpp
> +  DWORD attributes = GetFileAttributes(path.c_str());
If you're not familiar with Windows, either get familiar, or don't write Windows-specific code (nobody asked you to, and it's not necessary here). There's no excuse for submitting uncompiled and untested code for merging.

2022-08-31 15:09 UTC, iltis42 commented
> > Since this function will never be used on Windows, just omit it there.
> 
> ... which you did not, instead you omitted the preprocessor check, and now the Windows build is broken again.
Yes i see, we need to mask the whole function for windows and i need compile locally first, it will take a bit time...

2022-08-31 15:15 UTC, iltis42 commented
> > If the content is okay, i can quickly cleanup into a single one.
> 
> No, I won't spend time checking the contents of this mess. And no, folding all to a single commit is no "cleanup", it's more "messup" because I explicitly asked you _not_ to submit this as a single commit, remember?

Not clear to me what exactly is wrong, and I need advice what is exactly bad in all the commits, and what i needed to change.
Is it about the code itself, the checkin comment or the individual change i made for each of your comments ?
Grooming them into one seems also wrong, so what is exactly the point ?

2022-08-31 15:17 UTC, MaxKellermann commented
For example, the new commit "remove namespace File from TTYPort" is bad because it is a fixup for a known-bad commit that was not yet merged. Instead of adding fixup commits, amend existing known-bad commits.

2022-08-31 15:20 UTC, MaxKellermann commented
Hint: use stgit to manage PR branches! https://stacked-git.github.io/
I recommend stgit all the time, but nobody ever uses it, and then those people keep struggling with their PR branches, and eventually give up in frustration. There are good tools for the task, use them!

2022-08-31 15:48 UTC, iltis42 commented on src/system/FileUtil.cpp
> +  DWORD attributes = GetFileAttributes(path.c_str());
Masked this function for Windows completely, compilation for WIN64 target now is fine in docker. I run now also run all the other targets locally first. 

+#ifdef HAVE_POSIX
 bool
 File::IsCharDev(Path path) noexcept
 {
   struct stat st;
   return stat(path.c_str(), &st) == 0 && S_ISCHR(st.st_mode);
 }
+#endif

2022-08-31 16:38 UTC, MaxKellermann commented
Hey, look how simple those commit diffs now look! Very good!
Now the commit messages ... and the linker failures.

2022-08-31 16:40 UTC, iltis42 commented
> Hey, look how simple those commit diffs now look! Very good! Now the commit messages ... and the linker failures.

Yes, just w8 a moment, we are checking why, docker targets all compiled.

2022-08-31 19:46 UTC, MaxKellermann commented
Now we have 3 commits, 2 of which are bad.

2022-08-31 20:06 UTC, iltis42 commented
> Now we have 3 commits, 2 of which are bad.

More details please about the 2 commits, the 2 first i guess. What exactly should be improved in the commit messages ?

2022-08-31 21:09 UTC, MaxKellermann commented
The second commit is bad for 2 reasons:
- bad commit message, no explanation, no "closes" tag (do I really have to repeat this over and over?)
- causes linker failure

The third commit is bad because it is just a fixup for the second commit. Its commit message is also bad because it doesn't explain why this needs to be done, but that's not relevant because this commit shouldn't exist.

2022-09-01 07:40 UTC, MaxKellermann commented
The commit message is still devoid of an explanation. Sigh. You keep making me repeat myself, that is tiring.

2022-09-01 07:58 UTC, iltis42 commented
> The commit message is still devoid of an explanation. Sigh. You keep making me repeat myself, that is tiring.

You are talking about the second commit as below here, right?

"Improved device file descriptor check to avoid masking on android where executable bit may be set and linker dependencies, closes https://github.com/XCSoar/XCSoar/issues/1012"

IMHO i have provided a brief and good explanation for this one liner changeset in TTYEnumerator.cpp, e.g. what is exactly done: "improved file descriptor check", have tried to explained what is achieved by this: "avoid masking on android where executable bit may be set", have mentioned the linker dependencies and there is also a reference to the issue that is being closed by the closing tag #1012 containing more details.
Sure we can add more details, but i have no clue what aspect am i missing here ?

2022-09-01 08:11 UTC, MaxKellermann commented
What does "and linker dependencies" mean? This part of the sentence is completely confusing.

"Improved device file descriptor check" - improve how? What was wrong before? How does it solve the problem?

"to avoid masking on android where executable bit may be set" - mask what? On Android, what, Android? This is not an Android specific problem; it is a workaround for a bug on certain very rare proprietary buggy devices, which just happen to run Android. I don't know which devices those are - but if you develop a workaround, it should be well-documented with enough details.

You could also explain it from another angle, and say that the function you changed is supposed to identify accessible character devices, and that the execute bit doesn't have anything to do with what is supposed to be checked, and that this check is dispensable; instead, if one wants to check for character device, one should actually check for character devices.

That sounds ridiculously obvious, once you read this explanation, but it's not obvious when you see your commit diff, and it gets *less* obvious from reading your commit message, because your commit message is so confusing.

When I joined XCSoar 13 years ago, it was workaround stacked on top of workaround stacked on top of workaround, it was workarounds all the way down, and nobody knew what some piece of code was for, and nobody knew how those workarounds worked or why they worked. It was chaos. That's a state that must be prevented to happen again at any cost.

2022-09-01 08:35 UTC, iltis42 commented
> You could also explain it from another angle, and say that the function you changed is supposed to identify accessible character devices, and that the execute bit doesn't have anything to do with what is supposed to be checked, and that this check is dispensable; instead, if one wants to check for character device, one should actually check for character devices.
Have considered this advice now in latest commit

2022-09-01 08:50 UTC, MaxKellermann commented
Again you managed to phrase your commit message as complicated as possible. I was tired of this and wrote a new one: e042bb63a32a810d6ff1262565fba4035ef95daa
I hope it's obvious how much more informative and more comprehensible that is.

2022-09-01 08:50 UTC, closed without merging