Use the proper unit
XCSoar/XCSoar pull request #1038
Opened 2022-09-04 19:09 UTC by xtophe80

Brief summary of the changes
----------------------------

Fix typo in radio frequency unit.

2022-09-05 14:27 UTC, lordfolken requested changes

2022-09-05 14:27 UTC, lordfolken commented on src/InfoBoxes/Panel/RadioEdit.cpp
> +  RadioOffsetButtons(bool active_freq):OffsetButtonsWidget(UIGlobals::GetDialogLook().button, _T("%.0f kHz"), 5, 1000),set_active_freq(active_freq) {}
* Readd the noexcept
* Readd the linebreak

Make your commit message more meaningful:
InfoBox/RadioEdit: fix typo in frequency unit

2022-09-05 14:27 UTC, lordfolken commented on src/InfoBoxes/Panel/RadioEdit.cpp
> +  RadioOffsetButtons(bool active_freq):OffsetButtonsWidget(UIGlobals::GetDialogLook().button, _T("%.0f kHz"), 5, 1000),set_active_freq(active_freq) {}
Thank you for contributing!

2022-09-05 14:31 UTC, MaxKellermann commented
The commitdiff is unnecessarily confusing; it changes the coding style, removes `noexcept`, when all it should really do is change 'K' to 'k'.
The commit message is not helpful.

2022-09-09 08:21 UTC, MaxKellermann commented
b19dd6e4234aa78a16c9f6978d8df0da2d2c1762

2022-09-09 08:21 UTC, closed without merging