enhanced artificial horizon
XCSoar/XCSoar pull request #1261
Opened 2023-07-05 13:10 UTC by qubolino

Brief summary of the changes
----------------------------
enhanced artificial horizon (square, with marks)

Related issues and discussions
------------------------------
not suitable for aerobatics

2023-07-05 18:56 UTC, lordfolken requested changes
In general when you make commits then they should incremently change the code. 
Here you made changes, that you later commented or redid. 
* Your git history should be incremental steps to the final results.
* Every commit should compile. 
* Changes should be atomic.
* Commit messages need to be of the format: 

```
<component>: <change short version>
  longer text if needed. 
```

Comments on PRs are only for github. Git commits are forever.

2023-07-05 18:56 UTC, lordfolken commented on src/Look/HorizonLook.cpp
> +  // sky_pen.Create(Layout::Scale(1), LightColor(sky_color));
No commented lines please.

2023-07-05 18:56 UTC, lordfolken commented on src/Look/HorizonLook.hpp
> +  static constexpr Color sky_color{0x13, 0x9c, 0xff};
Again history broken...

2023-07-05 18:56 UTC, lordfolken commented on src/Renderer/HorizonRenderer.cpp
> +  canvas.DrawLine({center.x + radius/10, center.y + radius / 10}, {center.x + radius/10, center.y});
Again broken history. if you move lines around then changes to them are not apparent.

2023-07-05 18:56 UTC, lordfolken commented on src/Renderer/HorizonRenderer.cpp
> +  // canvas.DrawLine({center.x - 2, center.y}, {center.x +2, center.y});
commented line...

2023-07-05 18:56 UTC, lordfolken commented on src/Look/HorizonLook.cpp
> +  terrain_pen.Create(Layout::Scale(1), terrain_color);
Doing things this way, ruins the change view and makes it hard to review your commit.

2023-07-05 18:56 UTC, lordfolken commented
Out of curiosity, why do you say its not for aerobatics?

2023-07-05 18:58 UTC, lordfolken commented
Does it render well, when its in the infobox?

2023-07-05 19:00 UTC, lordfolken commented
In general a big improvement of what was! Stick with it so we can get the code to a good standard.

2023-07-15 06:43 UTC, MaxKellermann commented
> well i use git a bit differently and i imagine i should shrink all my commits into one to keep only incremental steps.

I don't know what that means, but certainly this PR should have more than one commit because it looks like this PR changes at least two independent things ("square" and "marks"). Each independent feature change must be one commit. Each refactoring change should be one commit.

Thanks @lordfolken, I agree that it is currently impossible to review this PR, it's a big mess.

2023-07-17 16:18 UTC, closed without merging