Renderer/HorizonRenderer: more elaborate artificial horizon
XCSoar/XCSoar pull request #1266
Opened 2023-07-19 09:54 UTC by qubolino

more elaborate artificial horizon with standard colorblind-friendly colors, shape and marks

Brief summary of the changes
----------------------------

Related issues and discussions
------------------------------

2023-07-19 10:04 UTC, MaxKellermann commented
You requested a review, but your code was already reviewed in https://github.com/XCSoar/XCSoar/pull/1261 and apparently you didn't obey the review. I wish you hadn't closed https://github.com/XCSoar/XCSoar/pull/1261 because now we're wasting time on doing the same again.

2023-07-19 11:03 UTC, qubolino commented
i did spend quite some time complying to what lordfolken advised. 

if that still needs work to meet your standards, i suggest you do it yourself, or ditch my work that i happily tried to share with the community

2023-07-19 11:14 UTC, MaxKellermann commented
> i did spend quite some time complying to what lordfolken advised.

Just look at the **very first** review comment: https://github.com/XCSoar/XCSoar/pull/1261#discussion_r1253499298

Then look at this piece in this PR you just submitted:
```
   // sky_pen.Create(Layout::Scale(1), LightColor(sky_color));
```
The is the very line @lordfolken criticized, and it's still there. You didn't reply to his comment and you did not fix this.

I stopped reading your PR after seeing this, but I should have stopped reading after seeing that your commit message doesn't even explain what your proposed change is about.

2023-07-19 11:20 UTC, MaxKellermann commented
Oh no, now you suggest merging a merge commit. Everything is wrong with this PR.

I suggest you should continue working on https://github.com/XCSoar/XCSoar/pull/1261 and not this one, because over there, you see unresolved review comments.

Your last post sounded like you don't want to do that. That's okay for me, you can do whatever you want, and you don't need to listen to us. But it might cause us not listening to you either.

2023-07-19 11:21 UTC, lordfolken requested changes
Thank you for sticking with it. A few minor points in my current review. 
Next i'll try to compile and run your code.

2023-07-19 11:21 UTC, lordfolken commented on src/Look/HorizonLook.cpp
> +  aircraft_brush.Create(Color(0xf2, 0xf2, 0x19));
Plsease make a definition for Color(0xf2, 0xf2, 0x19)  in HorizionLook.hpp, and reuse the definition here.

2023-07-19 11:21 UTC, lordfolken commented on src/Look/HorizonLook.cpp
> +  // sky_pen.Create(Layout::Scale(1), LightColor(sky_color));
Please remove commented line

2023-07-19 11:21 UTC, lordfolken commented on src/Look/HorizonLook.cpp
> +  // terrain_pen.Create(Layout::Scale(1), LightColor(terrain_color));
Please remove commented line

2023-07-19 11:21 UTC, lordfolken commented on src/Renderer/HorizonRenderer.cpp
> +#include <iostream>
Do we need this include? I haven't seen a function that uses it, but haven't tried to remove it yet.

2023-07-19 11:21 UTC, lordfolken commented on src/Renderer/HorizonRenderer.hpp
> +
Surplus line. Please remove.

2023-07-19 11:21 UTC, lordfolken commented on src/Renderer/HorizonRenderer.cpp
> +
Surplus line.

2023-07-19 11:25 UTC, lordfolken commented
Git history:
we like rebased code on current master. Merges aren't optimal. 
do a 
git pull origin master --rebase on your branch, commit your code and do a force push here.

2023-07-19 11:29 UTC, lordfolken commented
Max isn't very tolerant of when things aren't done in the way he expects. 
He is however fair when the code is well written (and i thnk the code is clear and good) and will merge it. 
I'll try to help get things into shape with you.
So just stick with it and don't get discouraged.

2023-07-19 11:30 UTC, lordfolken commented
@MaxKellermann i'll reopen, when i think it looks presentable.

2023-07-19 11:33 UTC, lordfolken commented
@iltis42 and @XCNav can you have a look at this? i think your customers would benefit mostly.

2023-07-19 11:40 UTC, MaxKellermann commented
> Max isn't very tolerant of when things aren't done in the way he expects.

First of all, I expect people to handle the existing reviews before asking for another review. @qubolino ignored the previous review, while pretending he "complied" (which I proved wrong). Then he explained he didn't want to meet our standards and asked me to do it for him. I certainly won't do that.

And this isn't event arguing whether commented line would be acceptable. At this point, this isn't about the code at all. It's about @qubolino's behavior towards code reviews.

2023-07-19 12:23 UTC, qubolino commented
dear max. i suggest you try be more tolerant on others skills. 

i respect your work, and you probably are a very skilled programmer. 

i opened a new pr b/c i've been asked to put everything in one commit. i don't know how to do this working with an existing pr. i actually don't know how to work with git as you already know. in fact i don't know how to do many things. 

one thing i know though is how to propose the perhaps only mediocre result of my work to the community -- despite the fact i benefited from a surely high standard result of its work. this pr was initially more a pull proposition than a request. i initially didn't envision to do anything more on it. then i thought it was maybe not too hard to comply and could make an effort and i did.

2023-07-19 12:28 UTC, qubolino commented
> Max isn't very tolerant of when things aren't done in the way he expects. 
> 
> He is however fair when the code is well written (and i thnk the code is clear and good) and will merge it. 
> 
> I'll try to help get things into shape with you.
> 
> So just stick with it and don't get discouraged. 

he isn't very tolerant of probably many more things than this. 
he imvho has a gift though. he is very good at discouraging people to contribute to something he doesn't own. the community does. fine by me. three times i interacted with him, three times i seemed to be completely wrong and felt my work was treated disrespectfully.

2023-07-19 12:37 UTC, MaxKellermann commented
@qubolino you're trying to reframe your failure to read review comments carefully, making it sound like it's about me. Please don't make this personal. This doesn't help, you're only wasting more of everybody's time with a pointless off-topic discussion that leads nowhere.

(You have annoyed me enough that I'm going to unsubscribe from this PR and I'm not going to spend more time on reviewing it. Bye.)

2023-07-19 13:02 UTC, qubolino commented
i find your behaviour very childish and non-constructive. but that's only my opinion.

speaking about being constructive, @lordfolken thanks a lot for (twice already) trying to encourage me to carry on. i'll be happy to work with you.

2023-07-19 13:06 UTC, qubolino commented
so #1 seems to make the pr square. which should i use? how do i make it acceptable for you (not even talking about the code content yet)?
only one commit, no merge? thanks for helping and for applying your pedagogical skills.

2023-07-19 15:51 UTC, qubolino commented
@lordfolken thanks for your comments, i addressed them, i think.

looking fwd to your constructive critics

2023-07-19 16:14 UTC, DanD222 commented
@qubolino 
If you look here https://github.com/XCSoar/XCSoar/pull/1266/commits, you'll see two new commits called "addressing" - you want to avoid that (as well as the "_Merge branch 'XCSoar:master' into master_" commit). If the PR was merged in this state, then XCSoar's commit history would include a whole bunch of "addressing" commits, as well as the wrong commits they fix.


What you might want to do instead is squash the "addressing" commit with the commit where the code that you're addressing is - it then becomes one commit with the right/addressed code.

After that, you Force Push from your local machine to your online Git repo - this rewrites the commits in the Pull Request, gets rid of the extraneous commits, and provides a nice commit set for review (providing the commit history is correct on your machine in the first place).

Regarding the "_Merge branch 'XCSoar:master' into master_" commit, you want to Rebase your branch on origin/master instead - this brings your branch up to date, but doesn't include the unnecessary merge commit.

(Not sure what your workflow is and sorry if I'm stating the obvious, but you can't do any of this through the Github web UI - this needs to be done on your local machine through an IDE/Git GUI/Git commands)

2023-07-20 05:54 UTC, qubolino commented
i squashed everything in one commit

2023-08-04 17:26 UTC, lordfolken commented
Finally got around to testing it. So the main window looks good to me and seems to behave properly. The Attitude Infobox, has some errors. Its not filling the whole square and the lines are not adapting to the smaller resolution. 
Your commit is missing a new line at the end.

2023-08-04 17:26 UTC, lordfolken commented
Finally got around to testing it. So the main window looks good to me and seems to behave properly. The Attitude Infobox, has some errors. Its not filling the whole square and the lines are not adapting to the smaller resolution. 
Your commit is missing a new line at the end.

2023-10-12 06:32 UTC, qubolino commented
> the yellow arrow should as well move with the bank as long the yaw is not changing
in old mechanical (but also traditionally) the yellow is not moving relative to the plane (nor is anything due to the yaw)
> The small infobox is overloaded
agreed and addressed. i kept only ground sky and plane in yellow

2023-10-12 06:33 UTC, qubolino commented
> the yellow arrow should as well move with the bank as long the yaw is not changing

in old mechanical (but also traditionally) the yellow is not moving relative to the plane (nor is anything due to the yaw)

> The small infobox is overloaded

agreed and addressed. i kept only ground sky and plane in yellow

2023-10-12 07:04 UTC, XCNav commented
![Screenshot_20231012_084527_Photos](https://github.com/XCSoar/XCSoar/assets/78668199/c93d7706-caab-4ca4-bf1f-608064543689)
Here you can see how yaw is handled at modern EFIS Aircraft Avionics. The yaw indicator is the little white bar below the white bank angle arrow. They both move basically in one unit. As the Aircraft slips the white bar is diverting from its position to the left or to the right. Maximum deflection is one bar width. Is the nose yawing to the left, the bar is diverting to the right and vice versa.

2023-10-12 11:04 UTC, qubolino commented
> Here you can see how yaw is handled at modern EFIS Aircraft Avionics

what you describe isn't yaw https://en.wikipedia.org/wiki/Yaw_(rotation). 
it's a slip indicator.
and there are different conventions for different efis.

my implementation of the horizon only takes into account roll and pitch. 
and i chose the convention of yellow isn't moving relative to aircraft.
https://en.wikipedia.org/wiki/Attitude_indicator

2024-02-19 21:39 UTC, lordfolken requested changes

2024-02-19 21:39 UTC, lordfolken commented on src/Renderer/HorizonRenderer.cpp
> +      canvas.DrawText(p2, buffer);
Buffer overflow when actually using the formatting at its length. Don't forgett the Null Terminator.

2024-02-19 21:39 UTC, lordfolken commented on src/Renderer/HorizonRenderer.cpp
> +      canvas.SetTextColor( COLOR_WHITE);
Space uneccessary

2024-02-19 21:39 UTC, lordfolken commented on src/Renderer/HorizonRenderer.cpp
> +      sprintf(buffer, "%+3d", k);
Potential buffer overflow

2024-02-19 21:39 UTC, lordfolken commented on src/Renderer/HorizonRenderer.cpp
> +char buffer[3];
Unused?

2024-02-19 21:39 UTC, lordfolken commented on src/Renderer/HorizonRenderer.cpp
>                                corners[i+1], intersect_left);
Out of bounds for corners[5]

2024-02-19 21:39 UTC, lordfolken commented on src/Renderer/HorizonRenderer.cpp
> +#include "LogFile.hpp"
Debugging?

2024-02-19 21:39 UTC, lordfolken commented on src/Look/HorizonLook.hpp
> +  Pen aircraft_pen;
Please keep color definitions in Look/HorizonLook.hpp

2024-02-19 21:39 UTC, lordfolken commented on src/Renderer/HorizonRenderer.hpp
> +}
Missing newline

2024-04-21 04:29 UTC, lordfolken commented
@qubolino if you are still around, can you have a look?

2024-05-21 19:14 UTC, merged

2024-07-02 16:24 UTC, qubolino commented
my focus was elsewhere @lordfolken. thanks a lot for merging!
will try work better with you guys in the future

2024-07-02 18:17 UTC, lordfolken commented
@qubolino i'm sure there is bugs and optimizations that are needed in there. Also further functionality such as  a speed/altitude tape etc. so if you would continue to maintain and help, i'd be very happy.