NM distance and compass point direction in "what is there" dialog
XCSoar/XCSoar pull request #1386
Opened 2024-03-15 23:20 UTC by xtophe80

This set of commits add the distance in nautical miles and the direction as a point of the compass to the Map item dialog aka "what is there" dialog.
Mainly for ease of position reporting with ATC. There is a toolbox for that but I find it's wasting real estate for the occasional use.

2024-03-16 18:03 UTC, xtophe80 commented
Doesn't compile on Windows due to my poor string handling. Also forgot about i18n and l10n. 
So no need to review

2024-03-16 20:07 UTC, lordfolken commented
> This set of commits add the distance in nautical miles and the direction as a point of the compass to the Map item dialog aka "what is there" dialog. Mainly for ease of position reporting with ATC. 

>There is a toolbox for that but I find it's wasting real estate for the occasional use.

You do realize that there are 3 or 4 Infobox sets that you can assign to additional pages?

2024-03-16 20:29 UTC, xtophe80 commented
> > There is a toolbox for that but I find it's wasting real estate for the occasional use.
> You do realize that there are 3 or 4 Infobox sets that you can assign to additional pages?

Indeed.  It's all about what is the less disturbing/more streamlined. Going back and forth between the normal page and the aux page or opening and closing the dialog. At the moment I haven't flown with that patch, so only better in my head, no practical experience.

2024-03-19 00:02 UTC, lordfolken commented
Please integrate your fix up commit, in the first commit where the changes are relevant.

2024-04-28 19:52 UTC, lordfolken requested changes

2024-04-30 13:48 UTC, xtophe80 commented
I will but very slowly.
I think I'll need to get a windows build environment to fix my code.
I understand the macosx failure is generic and not due to my commit.

Also should it be made an configurable feature ?

2024-05-08 22:56 UTC, xtophe80 commented
That should fix the strings issues on windows.

Now I need to see to make it configurable

2026-03-29 12:16 UTC, lordfolken commented
@coderabbitai full review

2026-06-01 17:02 UTC, lordfolken commented
@xtophe80 Hi — this draft has been open a while. Are you still planning to move it forward?

I've added the standard PR template/checklist to the description. When you have time, a rebase onto current `master` and ticking off the test plan would help us review. Happy to take another look once you're ready (or if you want feedback on the approach before polishing).

2026-09-10 23:48 UTC, lordfolken commented
Closing this draft as stale: there has been no update for over a year.

If you still want to proceed, please rebase onto current master and open a new pull request.

2026-09-10 23:48 UTC, closed without merging