Infoboxes/Content: add estimated task speed infobox
XCSoar/XCSoar pull request #1429
Opened 2024-05-16 01:18 UTC by ericcarden

This change adds estimated task speed (the value currently shown as "Speed estimated" on the Status-Task panel) to the list of available infoboxes. This could be a desirable infobox in a speed record attempt flight. I recently missed such a record by less than the duration of one circle, and I'd have probably left the last thermal at least one circle sooner (and gotten the record) had I been able to see this value without having to go back and forth to the Status-Task panel to see it.

This change also changes "cross country" to "cross-country" in every infobox description that contained "cross country". Previously, infobox descriptions were inconsistent regarding whether "cross country" or "cross-country" was used. It also tidies up the Type enum in Type.hpp (to make the most recent additions look like the earlier ones - just whitespace and comment changes), since a new item was being added here, anyway.

2024-05-16 20:01 UTC, lordfolken requested changes
hi, 
Implementation looks ok to me. 
Things to change:
  * commit message, while your motivation behind this pr is valid and interesting, i think it should be concise and to the point of what the commit does.
  *  The whitespace change should be a separate commit
  *  The cross-country  "-" correction also.

2024-05-16 20:01 UTC, lordfolken commented
@Scumi can you have a look?

2024-05-16 20:44 UTC, ericcarden commented
Thanks for reviewing this. I'll make those changes and send new pull
requests. I assume the longer (as is) description is still okay/desirable
for the PR, just not for the commit. If I'm wrong, let me know.

Thanks,

Eric

On Thu, May 16, 2024 at 3:01 PM Philipp Wollschlegel <
***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> hi,
> Implementation looks ok to me.
> Things to change:
>
>    - commit message, while your motivation behind this pr is valid and
>    interesting, i think it should be concise and to the point of what the
>    commit does.
>    - The whitespace change should be a separate commit
>    - The cross-country "-" correction also.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/XCSoar/XCSoar/pull/1429#pullrequestreview-2061763256>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAEZRGZBGFXRTCHQRWOIFQDZCUGCFAVCNFSM6AAAAABHZGIYJCVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDANRRG43DGMRVGY>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-05-16 22:44 UTC, ericcarden commented
A new pull request for just the infobox addition is submitted (#1431). Feel free to close this pull request (#1429) whenever you want. Thanks.

2024-05-16 23:31 UTC, lordfolken commented
You can just force push to your branch. You don't need to open new PRs.
If you want to edit your previous commit

git rebase -I HEAD~1

2024-05-18 00:56 UTC, ericcarden commented
Thanks. I have a lot to learn about git. I'll make a note of this for the
next time this situation comes up.

Eric

On Thu, May 16, 2024, 6:31 PM Philipp Wollschlegel ***@***.***>
wrote:

> You can just force push to your branch. You don't need to open new PRs.
> If you want to edit your previous commit
>
> git rebase -I HEAD~1
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/XCSoar/XCSoar/pull/1429#issuecomment-2116372700>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAEZRG6JN73IXFAI462U723ZCU6WBAVCNFSM6AAAAABHZGIYJCVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDCMJWGM3TENZQGA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-05-19 14:18 UTC, lordfolken commented
Can you close the other PRs please?

2024-05-19 21:36 UTC, ericcarden commented
This PR (#1429) isn't as we'd like it, but the newer one (#1431) is, I think. Would it be better to just close this one (#1429) and process the other (#1431)? I can do it the other way around (close #1431 and leave #1429 open), but that will take more work - to get #1429 modified to be like we'd like. Just let me know. Thanks.

2024-05-20 14:06 UTC, ericcarden commented
Disregard my last comment. I closed the other PR (#1431) and made the commit in this one (#1429) look just like the commit in the closed one (#1431). The requested changes are thus now in this (#1429) commit. Sorry for the confusion of creating the second PR (#1431).

2024-05-20 19:44 UTC, ericcarden commented
Got it. Thanks. I figured you had a good reason for asking for it this way. :-)

2024-05-21 00:01 UTC, ericcarden commented
I just noticed your edit to an earlier comment asking me to add an entry to NEWS.txt. Done. Let me know if there's anything else you'd like me to do. Thanks.

2024-05-21 05:37 UTC, lordfolken approved these changes

2024-05-21 05:37 UTC, merged