Handle ellipsoid and geoid altitudes
XCSoar/XCSoar pull request #1610
Opened 2024-11-08 15:04 UTC by moshe-braner

Proposed corrected and improved fix for issue #1605:
 * add ellipsoid altitude field to NMEAInfo & IGCFix structs
* fill in the ellipsoid altitude based on the GGA sentence
* output the ellipsoid altitude to the IGC file
* convert B-record altitude to AMSL
* only look up EGM96 approximation when necessary

Appears as 3 commits due to limitations of github web interface - feel free to "squash merge".

2024-11-09 00:06 UTC, lordfolken commented on src/Replay/IgcReplay.cpp
> +    basic.gps_ellipsoid_altitude = fix.gps_ellipsoid_altitude;
I think we should do this during parsing already.

2024-11-09 00:09 UTC, lordfolken requested changes
The unit tests need to be fixed `make check`.
commit messages should follow the general format:  filename: commit message

2024-11-09 00:49 UTC, moshe-braner commented
"commit messages should follow the general format: filename: commit message"
- do you want one commit per file?

2024-11-09 02:24 UTC, moshe-braner commented
reorganized commits and comments into https://github.com/XCSoar/XCSoar/pull/1611

2024-11-09 02:24 UTC, closed without merging

2024-11-09 04:27 UTC, moshe-braner commented
I am puzzled by the build failure for some targets (ubuntu) and not others
(android).  The error message is:

src/IGC/IGCParser.cpp:241: error: undefined reference to
'EGM96::LookupSeparation(GeoPoint const&)'
collect2: error: ld returned 1 exit status

which seems to be a linker, not compiler error?  I did add this line:

#include "Geo/Geoid.hpp"

to src/IGC/IGCParser.cpp, as was done in other files that call that
function (Device/Parser.cpp) and as you added to IGCParser.cpp in PR
#1607.  Does the order of the #include lines matter here?  Thanks.


On Fri, Nov 8, 2024 at 7:09 PM Philipp Wollschlegel <
***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> The unit tests need to be fixed make check.
> commit messages shoudl follow the general format: : commit message
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/XCSoar/XCSoar/pull/1610#pullrequestreview-2425088349>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AWI7NOUWWJJJ7IEKWR3YT3LZ7VHDTAVCNFSM6AAAAABRNVYT3GVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDIMRVGA4DQMZUHE>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-11-09 13:45 UTC, lordfolken commented
Please dont open a new pull request every time. Just fore push to your branch.

2024-11-09 15:31 UTC, moshe-braner commented
Assuming you meant "force push", I don't have a local clone, so could not
do that.  Trying to do this purely online in github.  So I had to create a
new branch from master and re-do the commits.

I see that, again, android build succeeded but ubuntu build failed.  Is
that something in my code?

Meanwhile I have realized (thanks to testing by nbonierre on an Android 10
smartphone of the Android binary created from PR #1610) that my code only
handles the case where the GNSS data is derived from NMEA sentences, but
when using the internal device in, e.g., Android, the data is obtained via
OS API calls, and thus my new ellipsoid altitude field is never filled in.
So need more work.  Could simply adjust the altitude just before writing to
the IGC file, as your original PR did, but that throws away the exact
ellipsoid altitude when known from the GGA sentence.  Also, depending on
the device, the original ellipsoid altitude may be available even when NMEA
is not used, e.g., in AndroidSensors.cpp if the device descriptor
"geoid_altitude" is false.


On Sat, Nov 9, 2024 at 8:45 AM Philipp Wollschlegel <
***@***.***> wrote:

> Please dont open a new pull request every time. Just fore push to your
> branch.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/XCSoar/XCSoar/pull/1610#issuecomment-2466222191>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AWI7NOSEX6HEKI7SFMBE5MDZ7YGXTAVCNFSM6AAAAABRNVYT3GVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDINRWGIZDEMJZGE>
> .
> You are receiving this because you modified the open/close state.Message
> ID: ***@***.***>
>

2024-11-11 16:24 UTC, lordfolken commented
The project provides both a docker container and a vagrant file under https://github.com/XCSoar/XCSoar/tree/master/ide These you can use to get a local development environment.