augment 3 InfoBoxes to provide information about thermaling efficiency
XCSoar/XCSoar pull request #784
Opened 2021-11-20 13:45 UTC by bomilkar

Brief summary of the changes
----------------------------

using 3 InfoBoxes' comment lines to better judge the quality of thermals. 

Related issues and discussions
------------------------------

This PR implements enhancements described in Issue #783

2021-11-21 15:46 UTC, lordfolken requested changes
please change the commit message to:
add average climb rate for the current thermal in TC_30s InfoBox

2021-11-21 18:48 UTC, lordfolken commented
All in all good PR. Please revise some of the comments and move the function in the other two libraries so it might be reused. :)

2021-11-21 19:06 UTC, bomilkar commented
_Please revise some of the **comments** and move the function in the **other two libraries** so it might be reused._

Which "comments" are you referring to??

Which "other two libraries" are you referring to??

2021-11-21 22:57 UTC, lordfolken commented
> _Please revise some of the **comments** and move the function in the **other two libraries** so it might be reused._
> 
> Which "comments" are you referring to??
> 
> Which "other two libraries" are you referring to??

Sorry ignore this comment please. Just look at the changes requested in the review.

2021-11-22 10:40 UTC, lordfolken requested changes

2021-11-25 16:12 UTC, bomilkar commented on src/InfoBoxes/Content/Thermal.cpp
> +  _tcscpy (buffer, duration_buffer);
I'll address this later if you want. But please not in this PR.

2021-11-25 16:13 UTC, bomilkar commented on src/InfoBoxes/Content/Factory.cpp
> +    N_("Total altitude gain/loss in the last thermal. The comment line: the overall climb rate for the last thermal."),
I reworded the help texts for the 3 commits.
@lordfolken I hope this is it now.

2021-11-26 16:06 UTC, MaxKellermann requested changes

2021-11-26 16:06 UTC, MaxKellermann commented on src/InfoBoxes/Content/Factory.cpp
> +    N_("Total altitude gain/loss in the last thermal. The number in smaller font reflects the overall climb rate for the last thermal."),
Can we "de-bloat" the wording here? I don't like the pharse "The number in smaller font reflects ...". Maybe just "Bottom: overall climb rate in the last thermal."

2021-11-26 16:06 UTC, MaxKellermann commented on src/InfoBoxes/Content/Factory.cpp
> +    N_("A 30 second rolling average climb rate based of the reported GPS altitude, or vario if available. The number in smaller font reflects the climb rate for the current thermal since circling sta
Same "de-bloat" here as well.
The phrase "since circling started" is redundant because "current thermal" implies that.

2021-11-26 16:06 UTC, MaxKellermann commented on src/InfoBoxes/Content/Thermal.cpp
> +  _tcscpy (buffer, duration_buffer);
Why not?

2021-11-26 16:07 UTC, MaxKellermann commented on src/InfoBoxes/Content/Factory.cpp
> +    N_("Total altitude gain/loss in the last thermal. The number in smaller font reflects the overall climb rate for the last thermal."),
Is "overall climb rate" really the right wording? "Average climb rate"?

2021-11-28 08:07 UTC, bomilkar commented
Average must specify a time frame. Otherwise the value is meaningless.

Let's stop wasting our time.

2021-11-28 08:07 UTC, closed without merging

2021-11-28 11:00 UTC, MaxKellermann commented
Yes, please, let's stop wasting our time. If you aren't willing to spend time on getting your code into shape, I'll remember that the next time I decide whether to spend time on reviewing your code.

2021-11-28 11:17 UTC, bomilkar commented
No worries. No more PRs from me.