Lua script input_event handling and update documentation
XCSoar/XCSoar pull request #886
Opened 2022-03-09 13:45 UTC by volkmarnissen

Fix bug in lua/InputEvent.cpp:
A lowercase key was not recognized by the Lua input_event.
Added ToUpperASCII in the Lua::FireKey method

Improved documentation in build.rst: Added reference to ubuntu 21 rsp.
debian 11

Added missing documentation in lua.rst.
input_event is now documented.
Input/InputEvents.cpp: If a lua function is configured in init.lua,
the event won't be passed to depreceated InputEvent handling anymore.

Brief summary of the changes
----------------------------

Related issues and discussions
------------------------------

Closes #885

2022-03-09 20:42 UTC, lordfolken requested changes
Please make your commit message more descriptive.

2022-03-09 22:16 UTC, volkmarnissen commented
Added more detailed information about all commits to the last commit message.
It also should solve the compile issue, which didn't occure locally.

2022-04-11 22:27 UTC, lordfolken requested changes
This is a full path, and shouldn't be here.

2022-04-11 22:28 UTC, lordfolken requested changes

2022-04-11 22:28 UTC, lordfolken commented on .gitignore
> +/sysroots/
full path. Shouldn't be a fully qualified path.

2022-04-12 09:26 UTC, MaxKellermann commented
A PR must not contain reverts or merge commits.

2022-04-12 09:39 UTC, MaxKellermann commented
Reset your PR branch to origin/master and cherry-pick all the commits you want to have in there, then force-push.
When I work on git branches, stgit is a valuable tool (I can't work without it). It helps you avoid the troubles you had.

2022-05-02 15:33 UTC, volkmarnissen commented
The willl be reopened with cleaned commits.

2022-05-02 15:33 UTC, closed without merging