Add support for Kobo Libra H2O
XCSoar/XCSoar pull request #889
Opened 2022-03-14 13:59 UTC by cmoetzing

The device has similar hardware as Kobo Clara HD.

Related issues and discussions
------------------------------
Closes #882

2022-03-14 14:02 UTC, MaxKellermann commented on src/Kobo/System.cpp
> +  if(DetectKoboModel() == KoboModel::CLARA_HD || DetectKoboModel() == KoboModel::LIBRA_H2O)
Line toooooooooooooooooooooooooo long

2022-03-14 14:26 UTC, cmoetzing commented on src/Kobo/System.cpp
> +  if(DetectKoboModel() == KoboModel::CLARA_HD || DetectKoboModel() == KoboModel::LIBRA_H2O)
add a line break

2022-03-14 14:30 UTC, cmoetzing commented on src/DisplayOrientation.hpp
> +    if(DetectKoboModel() == KoboModel::LIBRA_H2O) {
First of all: I am not a C++ developer. :)
I can compile the code and it runs on my Kobo (with correct screen input).
I have no idead what `constexpr` means. Can you please elaborate why the function should not be called here and what a solution would be?

2022-04-25 11:12 UTC, lordfolken commented
hmm you removed our workflows. You can disable the workflows in your repository settings.

2022-04-25 11:44 UTC, lordfolken requested changes
Checkout your branch before your changes and then do
```git cherry-pick <commitid>```
Then force push again. 
that way you can eliminate this change

2022-04-26 14:41 UTC, cmoetzing commented
I don't know if you allow global variables. Overall this is a cleaner version (I think). Open for suggestions.

2022-04-26 19:13 UTC, MaxKellermann commented
I'm confused by that commit diff. It moves chunks of code around, but it's documented to add a feature. I can't see what is really changed.

2022-04-27 12:27 UTC, cmoetzing commented
> I'm confused by that commit diff. It moves chunks of code around, but it's documented to add a feature. I can't see what is really changed.

Split it into several commits.

2022-07-19 08:09 UTC, MaxKellermann commented on src/DisplayOrientation.hpp
> +static DisplayOrientation default_display_orientation =
I don't understand this whole commit, and the commit message doesn't explain anything.

2022-07-19 08:12 UTC, MaxKellermann requested changes
I'm confused by this PR.

2022-07-19 08:12 UTC, MaxKellermann commented on src/Kobo/Model.cpp
> +void InitKoboModel() {
Bad coding style

2022-07-19 08:12 UTC, MaxKellermann commented on src/Kobo/Model.hpp
> +KoboModel GetKoboModel();
This is an API change which has nothing to do with Libra H2O, does it? This change obfuscates the commitdiff and makes review very hard. I don't even know why you're doing this; your commit message doesn't explain anything.

2022-07-19 08:12 UTC, MaxKellermann commented on src/Kobo/Model.cpp
> +    if (!ReadFromFile("/dev/mmcblk0", 0x200, buffer, sizeof(buffer)))
Bad indent, changed for no obvious reason to 4 spaces.

2022-07-19 08:12 UTC, MaxKellermann commented on src/Kobo/Model.cpp
> +    case KoboModel::LIBRA_H2O:
Bad indent.

2022-07-19 08:12 UTC, MaxKellermann commented on src/Kobo/PowerOff.cpp
> +  if (GetKoboModel() == KoboModel::GLO_HD)
Lots of changes unrelated to Libra H2O

2022-07-19 17:05 UTC, MaxKellermann commented
> Input and display does not work properly

What does that mean, exactly? "Does not work" is the worst possible problem description, because all it does is state the presence of the problem, but says nothing else.

>  The Libra uses a different default display orientation.

What does "default display orientation" mean in this context? How is it part of the problem?

> The above is why there are also changes in places general Kobo stuff is handled, not only Kobo Libra stuff.

You can do any number of things in one PR, those different things should be separate commits, or else you make it very hard to review your changes. The second thing that made your PR very hard to review is the lack of a good commit message; there was no explanation for anything.

2022-07-19 21:54 UTC, MaxKellermann commented
> With "default display orientation" I mean the literal meaning of the words: the orientation of the drawn Image on the screen if you do a fresh install on the device an power it up the first time without changing any settings. The default drawing direction of XCSoar means I see a 90° rotated image on the device which runs outside the screen edges so not the whole image is visible and touch input does not trigger actions under you finger but approx. 90° rotated aswell.

Where does this come from? Is the touch screen input rotated as well? What is the fb rotation setting?

2022-07-21 18:24 UTC, MaxKellermann commented
> How do I check?

`/sys/class/graphics/fb0/rotate` and `/sys/class/graphics/fbcon/rotate`

2022-07-25 06:46 UTC, cmoetzing commented
```
~ # cat /sys/class/graphics/fb0/rotate
3
```
File `/sys/class/graphics/fbcon/rotate` does not exist.

2022-09-01 21:16 UTC, ssosas commented
Hi all, I have a similar problem on Aura H2O with xcsoar v7.25. All works fine but display is mirrored (180°) and you need to guess where real buttons are to interact with the touchscreen.

Have you any v7.xx beta which fix that?

Many thanks!

2022-12-11 15:32 UTC, cmoetzing commented
Base on the recent support for the Libra 2 I updated my PR. It is indeed a lot cleaner now.

2022-12-11 18:40 UTC, merged